BEGIN;

ALTER TABLE source_registry
  ADD COLUMN IF NOT EXISTS vendime_checked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS prokurime_checked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS konsultime_checked BOOLEAN NOT NULL DEFAULT FALSE;

COMMIT;
